stages:
  data_ingestion:
    cmd: python src/Concrete_CS/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Concrete_CS/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/Concrete_Data.xls
  data_validation:
    cmd: python src/Concrete_CS/pipeline/stage_02_data_validation.py
    deps:
      - src/Concrete_CS/pipeline/stage_02_data_validation.py
      - configs/config.yaml
      - artifacts/data_ingestion/Concrete_Data.xls
      - params.yaml
    outs:
      - artifacts/data_validation/concrete_updated_data.csv
  data_transformation:
    cmd: python src/Concrete_CS/pipeline/stage_03_data_transformation.py
    deps:
      - src/Concrete_CS/pipeline/stage_03_data_transformation.py
      - configs/config.yaml
      - params.yaml
      - artifacts/data_validation/concrete_updated_data.csv
    outs:
      - artifacts/data_transformation/test_dataset_features.csv
      - artifacts/data_transformation/test_dataset_target.csv
      - artifacts/data_transformation/train_dataset_features.csv
      - artifacts/data_transformation/train_dataset_target.csv
  model_trainer:
    cmd: python src/Concrete_CS/pipeline/stage_04_model_trainer.py
    deps:
      - src/Concrete_CS/pipeline/stage_04_model_trainer.py
      - configs/config.yaml
      - params.yaml
      - artifacts/data_transformation/test_dataset_features.csv
      - artifacts/data_transformation/test_dataset_target.csv
      - artifacts/data_transformation/train_dataset_features.csv
      - artifacts/data_transformation/train_dataset_target.csv
    outs:
      - artifacts/model_trainer/concrete_model.pkl
