artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/compressive/Concrete_Data.xls
  local_data_file: artifacts/data_ingestion/Concrete_Data.xls
  
data_validation:
  root_dir: artifacts/data_validation
  data_validation_path: artifacts/data_ingestion/Concrete_Data.xls
  updated_data_validation_path: artifacts/data_validation/concrete_updated_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_transformation_path: artifacts/data_validation/concrete_updated_data.csv
  train_dataset_features_path: artifacts/data_transformation/train_dataset_features.csv
  train_dataset_target_path: artifacts/data_transformation/train_dataset_target.csv
  test_dataset_features_path: artifacts/data_transformation/test_dataset_features.csv
  test_dataset_target_path: artifacts/data_transformation/test_dataset_target.csv

model_trainer:
  root_dir: artifacts/model_trainer
  training_features_path: artifacts/data_transformation/train_dataset_features.csv
  training_target_path: artifacts/data_transformation/train_dataset_target.csv
  testing_features_path: artifacts/data_transformation/test_dataset_features.csv
  testing_target_path: artifacts/data_transformation/test_dataset_target.csv
  saved_file: artifacts/model_trainer/concrete_model.pkl